# Generated by Django 5.1.3 on 2025-02-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('address', models.TextField(default=' ')),
                ('desc', models.TextField(default=' ')),
                ('gender', models.CharField(default='male', max_length=10)),
                ('photos', models.ImageField(upload_to='Images')),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_person_number', models.CharField(max_length=10)),
                ('last_seen_loc', models.CharField(max_length=200)),
                ('missing_date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=10)),
            ],
        ),
    ]
