# Generated by Django 4.2.20 on 2025-04-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_mails'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='f_status',
            field=models.CharField(default='Not Found', max_length=10),
        ),
    ]
